name: Flutter CI

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./econnect
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ./econnect/pubspec.yaml
          cache: true

      -run: flutter build

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./econnect

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ./econnect/pubspec.yaml
          cache: true

      - run: dart format . --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    defaults:
      run:
        working-directory: ./econnect

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ./econnect/pubspec.yaml
          cache: true

      - run: flutter analyze .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ./econnect

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ./econnect/pubspec.yaml
          cache: true

      - run: flutter test
